#define TOGGLE_FOCUS_MODE_HOYKEY_ID 0x00
#define NEXT_WINDOW_HOTKEY_ID 0x01
#define PREV_WINDOW_HOTKEY_ID 0x02
#define QUIT_LIGHTWM_HOTKEY_ID 0x03
#define FORCE_TILE_LIGHTWM_HOTKEY_ID 0x04
#define WORKSPACE_LIGHTWM_HOTKEY_ID_BASE 0xFF

#define FOCUS_MODE_HOTKEY 'f'
#define NEXT_WINDOW_HOTKEY 'j'
#define PREV_WINDOW_HOTKEY 'k'
#define QUIT_LIGHTWM_HOTKEY 'q'
#define FORCE_TILE_LIGHTWM_HOTKEY 't'
#define WORKSPACE_LIGHTWM_HOTKEY_BASE '1'
