#define TOGGLE_FOCUS_MODE_HOYKEY_ID 0
#define NEXT_WINDOW_HOTKEY_ID 1
#define PREV_WINDOW_HOTKEY_ID 2
#define QUIT_LIGHTWM_HOTKEY_ID 3
#define WORKSPACE_1_LIGHTWM_HOTKEY_ID 4
#define WORKSPACE_2_LIGHTWM_HOTKEY_ID 5
#define WORKSPACE_3_LIGHTWM_HOTKEY_ID 6

#define FOCUS_MODE_HOTKEY 'f'
#define NEXT_WINDOW_HOTKEY 'j'
#define PREV_WINDOW_HOTKEY 'k'
#define QUIT_LIGHTWM_HOTKEY 'q'
#define WORKSPACE_1_LIGHTWM_HOTKEY '1'
#define WORKSPACE_2_LIGHTWM_HOTKEY '2'
#define WORKSPACE_3_LIGHTWM_HOTKEY '3'
