name: Build release
on: [push, workflow_dispatch]

jobs:

  build:
    permissions: write-all
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4

      - uses: christophebedard/tag-version-commit@v1
        id: new-tag
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version_tag_prefix: 'v'
          version_regex: 'Version ([0-9]+\.[0-9]+\.[0-9]+)'
        
      - uses: ilammy/msvc-dev-cmd@v1
      
      - name: Build executable and dll
        run: nmake

      - name: Create Release
        run: gh release create ${{ steps.new-tag.outputs.tag }} ./wm.exe ./wm_dll.dll -n "Version ${{ steps.new-tag.outputs.tag }}"
